services:
  postgres:
    image: nhothoang/postgre18.0:18.0
    container_name: postgres_db
    restart: unless-stopped
    env_file:
      - ./config_docker_compose/postgree.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./config_docker_compose/postgresql.conf:/etc/postgresql/postgresql.conf:ro
    command: [ "postgres", "-c", "config_file=/etc/postgresql/postgresql.conf" ]
    shm_size: 2g
    networks:
      - app_network

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
  redis:
    image: nhothoang/redis:8.2.2
    container_name: redis_server
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    volumes:
      - redis_data:/data
      - ./config_docker_compose/redis.conf:/usr/local/etc/redis/redis.conf:ro
    ulimits:
      nofile:
        soft: 100000
        hard: 100000
    sysctls:
      net.core.somaxconn: 1024
    networks:
      - app_network

    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  qdrant:
    image: nhothoang/qdrant:1.17
    container_name: qdrant_server
    restart: unless-stopped
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_storage:/qdrant/storage
      - ./config_docker_compose/qdrant.yaml:/qdrant/config/production.yaml:ro
    environment:
      QDRANT__STORAGE__STORAGE_PATH: "/qdrant/storage"
      QDRANT__LOG_LEVEL: "INFO"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    networks:
      - app_network

  minio:
    image: nhothoang/minio:07092025
    container_name: minio-server
    restart: unless-stopped
    env_file:
      - ./config_docker_compose/minio.env
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
      - minio_cache:/cache
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    networks:
      - app_network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
  embedding-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: nhothoang/embeding-bge-m3:latest
    container_name: embedding-service-bgem3
    restart: unless-stopped
    shm_size: 2g
    env_file:
      - ./config_docker_compose/embeding_bge_m3.env
    ports:
      - "6800:6800"
    volumes:
      - embeding_logs:/app/logs
    networks:
      - app_network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:6800/v1/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  postgres_data:
    name: postgres_data
  redis_data:
    name: redis_data
  qdrant_storage:
    name: qdrant_storage
  minio_data:
    name: minio_data
  minio_cache:
    name: minio_cache
  embeding_logs:
    name: embeding_logs
networks:
  app_network:
    driver: bridge
    external: true
